version: '3.8'

services:
  metadata:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-default_name}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - dfs_network


networks:
  dfs_network:
    external: true
