name: Metadata (*2) Deploy Pipeline for SNA Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          docker-compose build
      
      - name: Clean dangling images after build
        run: |
          docker image prune -f
  
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create network
        run: |
          docker network create dfs_network || true

      - name: Start test container
        run: |
          docker-compose run --name metadata-test -p 8080:8080 -d metadata
      
      - name: Wait for application to start
        run: |
          sleep 30
      
      - name: Test health endpoint
        run: |
          curl -f --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080/api/health/check
      
      - name: Stop test container
        run: |
          docker stop metadata-test
          docker rm metadata-test
      
      - name: Remove test image
        run: |
          docker rmi $(docker images -q '*metadata*:latest') || true
      
      - name: Clean dangling images after test
        run: |
          docker image prune -f
  
  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create network if not exists
        run: |
          docker network create dfs_network || true
      
      - name: Deploy first instance
        run: |
          CONTAINER_NAME=metadata-1 docker-compose -p m1 up -d
      
      - name: Deploy second instance
        run: |
          CONTAINER_NAME=metadata-2 docker-compose -p m2 up -d
      
      - name: Clean dangling images after deployment
        run: |
          docker image prune -f
